# site settings
title: Commonplace
subtitle: Un rincón de voces, escritos y reflexiones.
email: youremailaddress@gmail.com
description: Un espacio digital donde convergen citas, ideas y reflexiones que inspiran.
baseurl: "/commonplace" # the subpath of your site, e.g. /blog
url: andresmarrugo.net # the base hostname & protocol for your site
author: Andrés Marrugo
street_address: 
city: Cartagena de Indias
state: 
zip_code: 
country: Colombia
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/agmarrugo
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn: https://www.linkedin.com/in/andr%C3%A9s-marrugo-838aa883/
  Twitter: https://x.com/agmarrugo
  Facebook:
  Slack:

# build settings
markdown: kramdown

kramdown: 
  input: GFM
 
sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
